# api-deploy.cloudbuild.yaml contents

steps:
  # Print the full Pub/Sub message for debugging
  - id: "Echo Pub/Sub message"   
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo ${_BODY}

  # Cloud Run Deploy
  - id: "Deploy to Cloud Run"
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE_NAME}
      - --region=${_REGION}
      - --revision-suffix=${_REVISION}
      - --project=${_PROJECT_ID}
      - --allow-unauthenticated
      - --tag=${_IMAGE_TAG}
